name: Merge master into develop
on:
  push:
    branches:
      - master
jobs:
  mergeIntoDevelop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop          
      - name: set user name
        run: |          
          git config --global user.email "baturaartyom@inbox.ru"
          git config --global user.name "Artelf"   
      - name: merge master into develop
        run: |        
          git fetch --all
          git merge origin/master
          git push
  mergeIntoM1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: m1          
      - name: set user name
        run: |          
          git config --global user.email "baturaartyom@inbox.ru"
          git config --global user.name "Artelf"   
      - name: merge to m1
        run: |        
          git fetch --all
          git merge origin/develop
          git push